# Generated by Django 5.0.3 on 2024-04-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
